### PR TITLE
Fixes to work on Beta5.  Tested with 1.0.0-beta5-11781

### PR DESCRIPTION
**Pull request by MattGal**
Fixes problem noted occurring due to // in project.json, and then fixed caching APIs to work on latest.

### CODE REVIEW

**Comment by MattGal** [comment]
Ping?

**Comment by richlander** [comment]
@MattGal - You might @mention the specific people who you would like to review your change. That usually works for me.

**Comment by MattGal** [comment]
I @ctually tried but I can't resolve any of their names when I type @ :) I'll ask @xinshiMSFT ...

**Comment by EMaher** [comment]
My apologies for the delayed response.  Code looks fine.  Thanks.

**Pull request merged**
