### PR TITLE
add jekyll site with documentation

### PR DESCRIPTION
**Pull request by wbuchwalter**
@dcaro @dtzar 

- Copied documentation from `master` and `aspnet45` branches
- Markdowns have been renamed to work with Jekyll:  
  * Markdowns are now under the '_posts' folder and begin with a data
  * Mds related to .net Core are prefixed with `core`, mds related to 4.5 are prefixed with `45`
  * Assets (images, csv etc.) are all under the `assets` folder now

### CODE REVIEW

**Comment by dtzar** [comment]
There are some broken links inside the CD HOLs - they should reference the new html files you've created.
http://wbuchwalter.com/PartsUnlimited/core/core-cd.html
http://wbuchwalter.com/PartsUnlimited/45/45-cd.html
Would be good to check links to existing docs inside other HOLs too.

**Comment by dtzar** [comment]
Also - why do you put the date on the HOL md files?  Shouldn't the revision date in GitHub code be sufficient?

**Comment by dtzar** [comment]
Let's rename core deployment to "manual deployment"

**Comment by wbuchwalter** [comment]
Originally Jekyll is a blog platform, so every "blog post" needs to have a date so that jekyll picks it up correctly, otherwise it just won't display.
I will check if there is way to bypass that.

**Comment by wbuchwalter** [comment]
Everything is fixed.
Seems that there is no way to bypass the dates in the filenames.
See https://github.com/jekyll/jekyll/issues/120

**Comment by dtzar** [comment]
Thanks for the info! This was an interesting comment from there: "That's because "posts" are meant to be dated blog posts. Pages are for non-linear content."  Also an interesting idea from there is to just use 000-00* format.  It's not a big concern we must fix - just that over time people might think that the content isn't updated or really old just because of the file name.  Perhaps I'm over-thinking it...

**Comment by wbuchwalter** [comment]
Using the `0000-00-00` won't work unless a correct date is specified in the frontmatter in the post, which just moves the problem.
But I think we are fine, most likely only contributors will go to the `gh-pages` branch and the date of the last commit is clearly visible on each file, so we are covered I would say.

**Comment by dcaro** [comment]
As per the documentation https://jekyllrb.com/docs/posts/ you must name the files with the dates.

**Comment by dcaro** [comment]
@wbuchwalter  How much work would be required to update the full content if the name of the file change when we update it ?

**Comment by wbuchwalter** [comment]
@dcaro Not sure I understand what you mean. Each file require a prefixed date so that Jekyll detects it, but we don't ever need to change it after that. And the date isn't displayed anywhere on the website.

**Comment by dcaro** [comment]
If you want to update the content, you can either edit the existing page or create a new one with a new date and delete the previous one. In the latter case we could update the links to that page. If @dtzar is ok with the fact that dates are in the source code only, I'm fine with that as well.

**Comment by wbuchwalter** [comment]
The way Jekyll is configured today, the dates are not in the url.
For example CD for .NET Core will be at `/PartsUnlimited/core/core-cd.html`.
Also, you don't need to update the navigation bar on the left everytime new content is added, it's automatically added there at the correct place based on the category and the order specified in the frontmatter.
All this means that if we have the same content but with a different date it will create a duplicate in the website.
Also we lose the history of said file in git.

**Comment by dtzar** [comment]
Let's just keep the dates in the filenames.  Benefits are not worth the effort to change them.

**Comment by dcaro** [comment]
LGTM

**Pull request merged**
